# .github/workflows/main.yml
name: CI/CD Pipeline for Flask App

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use a GitHub-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to checkout your repository code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest Python 3 version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s . -p "test_*.py" # Discover and run tests

  deploy:
    needs: build-and-test # This job depends on build-and-test succeeding
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.9.0 # Use a specific version for stability
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # Use the secret for private key

    - name: Add EC2 Host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Deploy application files
      uses: appleboy/scp-action@v0.1.7 # Use a specific version
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "app.py,requirements.txt,test_app.py" # Files to transfer
        target: "/home/${{ secrets.USERNAME }}/my-flask-app" # Destination on EC2

    - name: Install dependencies on EC2 and Restart Gunicorn
      uses: appleboy/ssh-action@v1.0.0 # Use a specific version
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/${{ secrets.USERNAME }}/my-flask-app
          /usr/bin/python3 -m pip install -r requirements.txt # Reinstall dependencies
          sudo systemctl restart myflaskapp # Restart the Gunicorn service
